# fly.toml app configuration file generated for lineard on 2023-05-19T19:01:40+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lineard"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
