# fly.toml app configuration file generated for lineard on 2023-05-18T14:07:27+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lineard"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250